// Vitest port of the canonical lago-auth `verify_jwt` integration
// suite at `crates/lago/lago-auth/tests/verify_jwt.rs` (broomva/core/life
// commit `944f2ba9`).
//
// JWTs in this file are NOT generated by JavaScript — they were emitted
// by the Rust signer using the same master-seeds + `EcdsaP256Identity`
// the canonical test suite uses (`MasterSeed::from_bytes([N; 32])` →
// `derive_p256_key` → `EcdsaP256Identity::from_key_bytes` →
// `sign_agent_jwt`). The extracted byte-for-byte JWTs below let us
// verify the TypeScript port against the exact same wire payloads the
// Rust verifier accepts/rejects. See the PR body for the extractor
// command + commit SHA.
//
// File under test: ../verify-jwt.ts

import { describe, expect, it, vi } from "vitest";

vi.mock("server-only", () => ({}));

import { JwtError, verifyJwt } from "../verify-jwt";
import {
  type DidRotation,
  EmptyJournal,
  type JournalResolver,
  type RotationChainQuery,
} from "../rotation-chain";

// ---------------------------------------------------------------------------
// Test vectors (extracted from the canonical Rust signer — DO NOT EDIT)
//
// To regenerate: see /tmp/derive-keys/main.rs in the PR body, run
// `cargo run --release` against anima-identity v0.3.0.
// ---------------------------------------------------------------------------

/** seed=[7; 32] → identity used by `verify_jwt_es256_with_no_rotation`. */
const SEED7_DID =
  "did:key:zDnaed8XSmxNoJZmaAfViS7T3J2RmbnpCeh5MSFZcHE7uwmNM";
const SEED7_JWT =
  "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDprZXk6ekRuYWVkOFhTbXhOb0pabWFBZlZpUzdUM0oyUm1ibnBDZWg1TVNGWmNIRTd1d21OTSIsInR5cCI6IkpXVCJ9.eyJleHAiOjk5OTk5OTk5OTksInN1YiI6ImFndF8wMDEifQ.E5TZ1KigtcyKy_im1I7SutXlxoRQLLds-i2j1En9OZZcDPF1Z8zT00yQmtD62D0vqLtPSWbK2cnz73I0sOH7rw";

/** seed=[9; 32] → identity used by `verify_jwt_rejects_revoked_did`. */
const SEED9_DID =
  "did:key:zDnaeTgyNeH9a93vfZvgV3FjMaWxMNGf4njnXfi62Gs87yfch";
const SEED9_JWT =
  "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDprZXk6ekRuYWVUZ3lOZUg5YTkzdmZadmdWM0ZqTWFXeE1OR2Y0bmpuWGZpNjJHczg3eWZjaCIsInR5cCI6IkpXVCJ9.eyJleHAiOjk5OTk5OTk5OTksInN1YiI6ImFndF8wMDEifQ.bJA781qQDIgJToFCfJ4eTdAhockE4M9jbq9eByaq3384KVExmBLqrvNwJi6LaLh6_Tznp3zrSAmi5lUYKZYM7g";

/** seed=[1; 32] → "identity A" — used in the wrong-key + rotation tests. */
const SEED1_DID =
  "did:key:zDnaeUJAh6BncejKme6pGxJH8ChS6nRBn4YrmQ4XjmHkfMYsi";
const SEED1_JWT =
  "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDprZXk6ekRuYWVVSkFoNkJuY2VqS21lNnBHeEpIOENoUzZuUkJuNFlybVE0WGptSGtmTVlzaSIsInR5cCI6IkpXVCJ9.eyJleHAiOjk5OTk5OTk5OTksInN1YiI6ImFndF8wMDEifQ.hfrNqeQqABDkPj_mq27eM3UUi3nCJx1UgQRhos4v2xonmBTbVKMC8Ka6Ycwdr8gTnCpU_iZ6nXYa-rYHgukOsw";

/** seed=[2; 32] → "identity B" — the rotation target. */
const SEED2_DID =
  "did:key:zDnaeXtkR2xMA8sXokJotJw4gEpF73r7cCeF3BToysCWsgk5g";

/**
 * FORGED JWT — signed with key A's private scalar but stamped with B's
 * DID in `kid`. Exercises the wrong-key rejection branch.
 */
const FORGED_A_AS_B_JWT =
  "eyJhbGciOiJFUzI1NiIsImtpZCI6ImRpZDprZXk6ekRuYWVYdGtSMnhNQThzWG9rSm90Snc0Z0VwRjczcjdjQ2VGM0JUb3lzQ1dzZ2s1ZyIsInR5cCI6IkpXVCJ9.eyJleHAiOjk5OTk5OTk5OTksInN1YiI6ImFndF8wMDEifQ.S9ry6xN9W_Vi-D7PX5VU0DMjTzEzO9lX8F0M5PaAjiohrz8NbfFboDCZdLt0tpTywttnFDkaL0Zkkp6g24DNOw";

// ---------------------------------------------------------------------------
// In-memory journal mock — mirrors the `MockJournal` in
// `crates/lago/lago-auth/tests/verify_jwt.rs:46`.
// ---------------------------------------------------------------------------

class MockJournal implements JournalResolver {
  private rotations: DidRotation[] = [];
  private revoked: Set<string> = new Set();

  addRotation(rot: DidRotation): void {
    this.rotations.push(rot);
  }

  revoke(did: string): void {
    this.revoked.add(did);
  }

  async rotationEventsFor(
    _query: RotationChainQuery,
  ): Promise<readonly DidRotation[]> {
    return [...this.rotations];
  }

  async revocationEventFor(did: string): Promise<number | null> {
    return this.revoked.has(did) ? 42 : null;
  }
}

// ---------------------------------------------------------------------------
// 5 Vitest cases — ports of Rust `tests/verify_jwt.rs:84-148`
// ---------------------------------------------------------------------------

describe("verifyJwt — TypeScript port of lago-auth::verify_jwt", () => {
  // Rust test: `verify_jwt_es256_with_no_rotation` (verify_jwt.rs:84)
  it("verify_jwt_es256_with_no_rotation: verifies ES256 JWT under EmptyJournal", async () => {
    const journal = new EmptyJournal();
    const verified = await verifyJwt(SEED7_JWT, journal);
    expect(verified.alg).toBe("ES256");
    expect(verified.kidDid).toBe(SEED7_DID);
    expect(verified.effectiveDid).toBe(SEED7_DID);
    expect(verified.rotationChain).toHaveLength(0);
    expect(verified.claims.sub).toBe("agt_001");
  });

  // Rust test: `verify_jwt_rejects_revoked_did` (verify_jwt.rs:99)
  it("verify_jwt_rejects_revoked_did: rejects JWT signed by revoked DID", async () => {
    const journal = new MockJournal();
    journal.revoke(SEED9_DID);
    await expect(verifyJwt(SEED9_JWT, journal)).rejects.toThrow(
      /revoked/,
    );
  });

  // Rust test: `verify_jwt_rejects_wrong_signing_key` (verify_jwt.rs:114)
  it("verify_jwt_rejects_wrong_signing_key: refuses forged kid", async () => {
    // JWT signed with key A but advertises B as the kid. The verifier
    // resolves B's pubkey from the DID, then signature verification
    // fails because A's signature won't validate under B's key.
    const journal = new EmptyJournal();
    await expect(verifyJwt(FORGED_A_AS_B_JWT, journal)).rejects.toThrow(
      JwtError,
    );
    // The Rust test asserts the error message contains "verify"
    // (case-insensitive). We mirror that here.
    await expect(verifyJwt(FORGED_A_AS_B_JWT, journal)).rejects.toThrow(
      /verify/i,
    );
  });

  // Rust test: `verify_jwt_rejects_unsupported_alg` (verify_jwt.rs:133)
  it("verify_jwt_rejects_unsupported_alg: rejects HS256 before key lookup", async () => {
    // Hand-craft an HS256 JWT — same payload shape but advertised
    // algorithm is HS256, which is NOT in the AgentJwtAlg whitelist.
    // The verifier must refuse before doing any key resolution work.
    const header = { alg: "HS256", typ: "JWT", kid: "did:key:zDnFake" };
    const body = { sub: "agt", exp: 9999999999 };
    const headerB64 = base64urlEncode(JSON.stringify(header));
    const bodyB64 = base64urlEncode(JSON.stringify(body));
    const fakeJwt = `${headerB64}.${bodyB64}.deadbeef`;

    const journal = new EmptyJournal();
    await expect(verifyJwt(fakeJwt, journal)).rejects.toThrow(JwtError);
    await expect(verifyJwt(fakeJwt, journal)).rejects.toThrow(
      /unsupported agent JWT alg/,
    );
  });

  // Rust test: `verify_jwt_walks_chain_for_old_did` (verify_jwt.rs:148)
  it("verify_jwt_walks_chain_for_old_did: walks rotation chain and refuses A's sig under B's key", async () => {
    // JWT signed by A (kid=A). Journal records A→B rotation.
    // Verifier walks chain → effective_did = B → tries to verify A's
    // signature against B's pubkey → FAILS. The Rust test accepts
    // either "verify" or "mismatch" in the error message; we mirror.
    const journal = new MockJournal();
    journal.addRotation({
      oldDid: SEED1_DID,
      newDid: SEED2_DID,
      rotationProofJws: "proof",
      rotatedAtSeq: 100,
    });
    await expect(verifyJwt(SEED1_JWT, journal)).rejects.toThrow(JwtError);
    // Either alg/curve mismatch or signature verify failure is acceptable
    // (matches Rust assertion line 187: `verify OR mismatch`).
    await expect(verifyJwt(SEED1_JWT, journal)).rejects.toThrow(
      /verify|mismatch/i,
    );
  });
});

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function base64urlEncode(s: string): string {
  // Encode UTF-8 → bytes → base64url. `btoa` only handles Latin-1,
  // so we go via TextEncoder + a manual byte → base64 conversion to
  // keep this portable across Node + Edge.
  const bytes = new TextEncoder().encode(s);
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}
